planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
    range: 0.0
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - BKPIECEkConfigDefault
    - ESTkConfigDefault
    - PRMkConfigDefault
  projection_evaluator: joints(phantomx_pincher_arm_shoulder_pan_joint, phantomx_pincher_arm_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.01

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
