joint_limits:
  phantomx_pincher_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 2.0
  phantomx_pincher_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 2.0
  phantomx_pincher_arm_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 2.0
  phantomx_pincher_arm_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 2.0
  phantomx_pincher_gripper_finger1_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: true
    max_acceleration: 0.1
